language: python
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
      env:
        - PYTHON_MAJOR_VERSION=2.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
    - os: linux
      dist: trusty
      python: 3.4
      env:
        - PYTHON_MAJOR_VERSION=3.4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
            - python3-pip
    - os: linux
      dist: trusty
      python: 3.5
      env:
        - PYTHON_MAJOR_VERSION=3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
            - python3-pip
    - os: linux
      dist: trusty
      python: 3.6
      env:
        - PYTHON_MAJOR_VERSION=3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
            - python3-pip

    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=2.7
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.4
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.5
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.6

    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=2.7
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.4
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.5
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.6

    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=2.7
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.4
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.5
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.6
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      rvm get head --auto-dotfiles
      brew update;
      PYTHON_VERSION=$(pyenv install --list | grep "^$PYTHON_MAJOR_VERSION")
      pyenv install -s $PYTHON_VERSION
      pyenv global $PYTHON_VERSION
      # protoc
      pushd /tmp
      wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-osx-x86_64.zip
      unzip protoc-3.1.0-osx-x86_64.zip
      popd
      export PATH=/tmp/bin:$PATH
      # bazel
      brew install bazel
  fi
  if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      # protoc
      pushd /tmp
      wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
      unzip protoc-3.1.0-linux-x86_64.zip
      popd
      export PATH=/tmp/bin:$PATH
      # bazel
      wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel_0.4.4-linux-x86_64.deb
      sudo dpkg -i bazel_0.4.4-linux-x86_64.deb
  fi
install:
- pip install -U pip setuptools wheel protobuf numpy
script:
- source travis_installer.sh
- cd
deploy:
  provider: pypi
  user: zihaolucky
  password:
    secure: MeVZ1A6snRdaifnVYdZCNigyYMW/evFVtV6lGyVcNrea81n9WA9M32vbHq+Up1zs89BFsxK8M7uGIPXFuw9o2cuLnRU7ecz3yyYP/H7SKqxgljMn64Crrzmrpz/XnOaPMT7harqalrdFzOfB273Ab5GyVwUktmce3ZMYFvEixGtvgEEhgeAHTAt7DEZPfGNT9LGVkReZRmqG3o4dJnuzIX6lczWYTxgy0UKXzNsrjzs/OUaLvN8ryCGgSXHw/gntaN2rgO46MEXgRVb6g3MvZHh3HMy/3btHxdGm6YBDt+PLlpAeMUD2jpenJ7DZrYpq9FLuOcAnJFJfYPAq4aMBbNJCed6G/HLsV3augQkcIAw9x+6+9B5T/aA3xwEPObzHBIqNFvqM+xvwb7kEvcFsmkz0MU7xC7c3drq575+/i8oO3cimhBUEEc4F9/q7MOvPkAScBa97IDIAkdRJ1w7xvne6ILA02rlqNAaXj63zm2Qd7rI+1Khccjk7+99AcNg/DRCAshVpp5tnm03cyvoCKo/hJpO3bYb1jq3L1TONiBx77kYc9FJTnsQSjJYLPQpGQ01LlBYSIjEYC5gWJ7FMMV9yCHr6OFgPH73SRLTvu5BRRPQj2htkZxDhxCkcfczACXeZ7SRbQBTitsBzIdgZSnHiulalDhYSwImKRpNo81Q=
  distributions: bdist_wheel
  on:
    tags: true